### ISSUE TITLE
Use the Python 3.9 branch?

### ISSUE THREAD

**Issue by encukou** [JulienPalard/python-docs-cookiecutter#5]
I heard from a person interested in translating: 

> Alright, one more question: the new translation cookiecutter suggests to choose the 3.8 branch https://github.com/JulienPalard/python-docs-cookiecutter, which is probably outdated. Should I select master instead?

**Comment by encukou** [comment]
And another comment:
> The fact that the README doesn't use [git clone] --single-branch is pretty sad though, seeing how big is the whole repo

Maybe e.g. `git clone --single-branch --depth 1000` would be more appropriate.

**Comment by JulienPalard** [comment]
For the version, I fixed it, thanks for reporting, I almost forgot this repo :p

I also updated the makefile according to what we use today in france.

For "--single-branch" alone, it won't help, it's still fetching the whole history, and anyway I think users working on the translation may one day or another need a cpython repo, with at least the master branch, so they can for example fix a typo they spotted during translation. `--depth`  won't work without `--single-branch`, so no I prefer keeping it like that.

But during the CI we greatly limit the branch and the depth, though, if it can reassure your friend.

(while I'm at it I bet there's a cleaner way to do it, we're looping on different depth until we find the searched commit :p I bet we should try `--shallow-since` and/or `--shallow-exclude` maybe, I'll need to try, if nobody does it before me).

Don't hesitate to tell them I'm available to help here, on freenode, and by email (doc-sig mailing list).
